# This is a basic workflow to help you get started with Actions

name: Front End Development Projects

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    
    # Runs command to install surge using npm
    - name: Installing Surge
      run: npm install --global surge
      
    # Deploying code on Surge
    - name: Deplying on Surge
      run: surge ./ muhammad_abdullah_habib.surge.sh --token ${{}}
   
